package main;



public class InicioAplicacion {

	public static void main(String[] args) {

		
	
		boolean finAplicacion=false;
		
		//***************************** INICIO DE PROGRAMA *******************************
		
		//INCLUIR INTERFAZ DE BIENVENIDA
		
		//new.menu.menuInicio()  metodo que falta del paquete Angel
		
		//-------------------- EMPIEZA LA INTERACCION  CON EL USUARIO -----------------------
		
		
			
		//new gestion.ejecutarAplicacion();
			
		
		
		 //******************************  FIN DE PROGRAMA ***********************************
		
		
		
		
		
		//DESCRIPCIÓN:
		
		/*INTERFAZ OPCIONES QUE TENDRA LAS OPCIONES:
		 *
		 * 1-VUELO IDA (INTRODUCE: 
		 * 
		 * 				-ORIGEN
		 * 				-DESTINO
		 * 				-FECHA
		 * 				-NUMERO DE BILLETES A COMPRAR.
		 * 
		 *  		++COMPROBAR DATOS Y LLAMAR A LOS METODOS CORRESPONDIENTES DE LA CLASE GESTION.
		 *  		DESPUES DE PASAR TODOS LOS FILTROS SE GENERA UN/VARIOS  OBJETO/S VUELOS Y PERSONAS QUE DESPUES SE PASARAN 
		 *  		OBJETO/S BILLETE QUE SE CREE  Y QUE GUARDARA LOS DATOS ESPECIFICADOS
		 *  
		 *  			)
		 *  
		 * 2-VUELO IDA Y VUELTA( INTRODUCE:
		 * 
		 * 						-ORIGEN
		 * 						-DESTINO
		 * 						-FECHA
		 * 						-NUMERO DE BILLETES A COMPRAR
		 * 
		 * 			+SE CONSULTA PRIMERO EL/LOS VILLETE/S DE IDA Y SE MUESTRAN EL/LOS VILLETE/S DE IDA DISPONIBLES EN LA BD.
		 * 			+ACONTINUACION UN MÉTODO INVIERTE EL DATO DE ORIGEN EN DESTINO Y EL DE DESTINO EN ORIGEN Y
		 * 				HACE LA OPERACION DE CONSULTA Y LE MUESTRA LOS OPCIONES DE REGRESO.
		 * 
		 * 
		 * 		++ LOS METODOS LLAMADOS EN LAS ACCIONES ANTERIORES COMPRUEBAN LOS DATOS EN LA BD Y VA GUARDANDO LA INFO EN UN OBJETO BILLETE TANTAS VECES COMO VILLETES 
		 * 			SE GENEREN (2 COMO MINIMO (IDA Y VUELTA) O LA CANTIDAD DE BILLETESIDA-VUELTA QUE EL USERIO COMPRE)	
		 *	
		 * 3-VUELO+HOTEL (SALTA OTRA INTERFAZ:
		 * 					-IDA + HOTEL. (IGUAL QUE VUELO IDA PERO AHORA SE GESTIONA EL HOTEL, APARECERAN LOS HOTELES SEGUN EL ORIGEN ESPECIFICADO, SE COMPRUEBA LAS
		 * 								 PLAZAS SEGUN EL NUMERO DE BILLETES COMPRADOS. SE GENERA UN OBJETO RESERVA QUE CONTIENE: BILLETE+HOTEL)
		 * 
		 * 
		 * 					-IDA + VUELTA + HOTAL (IGUAL QUE VUELO IDA+VUELTA PERO AÑADIENDO EL HOTEL)
		 * 
		 * 				)
		 * 
		 * 4-SALIR DE LA APP (INTERFAZ DE DESPEDIDA DE LA APP)
		 * 
		 * 
		 * 
		 * 
		 * 
		 * 
		 * 			++ CUANDO SE HAYA HECHO UNA OPERACION ( LA COMPRA DEL BILLETE) SE PREGUNTARA AL USUARIO SI QUIERE REALIZAR OTRA OPERACION
		 * 				O QUIERE SALIR DE LA APP. 
		 * 
		 * 
		 */
	}

}
